// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArqFyrSH2vEL4vcj41D6AXOy0zC9-49qU',
    appId: '1:974704293118:web:b47a788b1da16a165fa1af',
    messagingSenderId: '974704293118',
    projectId: 'groumap-deda4',
    authDomain: 'groumap-deda4.firebaseapp.com',
    storageBucket: 'groumap-deda4.firebasestorage.app',
    measurementId: 'G-FLJKQRB54E',
    databaseURL: 'https://groumap-deda4-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDugWTKF1E8R_gh-LwE_mOuLXRdHy9D324',
    appId: '1:974704293118:android:1cc6d330d4ccee9c5fa1af',
    messagingSenderId: '974704293118',
    projectId: 'groumap-deda4',
    storageBucket: 'groumap-deda4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AlzaSyDuj669si-4QgfNqQWy0DwPrtjafiMtw4M',
    appId: '1:974704293118:ios:392c33797bff94c65fa1af',
    messagingSenderId: '974704293118',
    projectId: 'groumap-deda4',
    storageBucket: 'groumap-deda4.firebasestorage.app',
    iosBundleId: 'com.stocopo.groumap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AlzaSyDuj669si-4QgfNqQWy0DwPrtjafiMtw4M',
    appId: '1:974704293118:ios:392c33797bff94c65fa1af',
    messagingSenderId: '974704293118',
    projectId: 'groumap-deda4',
    storageBucket: 'groumap-deda4.firebasestorage.app',
    iosBundleId: 'com.stocopo.groumap',
  );
} 